Vagrant.configure("2") do |config|
  # Set the base box
  config.vm.box = "eurolinux-vagrant/centos-stream-9"
  #config.vm.box_version = "9.0.48"

  # Specify the network configuration (static IP and bridged)
  config.vm.network "public_network", bridge: "eth0", auto_config: true # For bridged networking
  config.vm.network "private_network", type: "static", ip: "192.168.56.10"  # Use your preferred fixed IP
  
  # Customize the virtual machine name
config.vm.define "centos9" do |centos9|
centos9.vm.hostname = "centos-vm"
end

  # Set the provider (default: VirtualBox, can be changed)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Set the RAM for the VM (1GB)
    vb.cpus = 2         # Set the number of CPUs
  end

  # Configure the VM to run with SSH access
#  config.vm.provision "shell", inline: <<-SHELL
 #   yum update -y
  #  yum install -y vim curl wget
 # SHELL
end
