# Vagrantfile for Ubuntu VM with Docker and GitLab CE
Vagrant.configure("2") do |config|
  # Specify the box to use (Ubuntu 22.04 LTS in this case)
  config.vm.box = "ubuntu/jammy64"

 config.vm.define "nexus" do |nexus|
    nexus.vm.hostname = "nexus"
  end
  # Customize the VM's resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"      # Set memory size (in MB)
    vb.cpus = 2             # Set number of CPUs
  end

  # Set up a private network with a static IP
  config.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6E AX211 160MHz", auto_config: true # For bridged networking
  config.vm.network "private_network", ip: "192.168.56.14"

#   config.vm.provision "shell", path: "provision.sh"
end
