spring:
  datasource:
    url: jdbc:postgresql://192.168.56.10:5432/books
    username: maximka
    password: maxypayne
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
