Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Utilisation d'Ubuntu 20.04

  config.vm.define "deployment" do |deployment|
    deployment.vm.hostname = "deployment"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"      # Set memory size (in MB)
    vb.cpus = 2             # Set number of CPUs
  end

  # Set up a private network with a static IP
  config.vm.network "public_network", bridge: "eth0", auto_config: true # For bridged networking
  config.vm.network "private_network", ip: "192.168.56.15"

#   config.vm.provision "shell", path: "provision.sh"
end
